### ISSUE TITLE
Setting to open file automatically when it's exported?

### ISSUE THREAD

**Issue by OliverBalfour** [OliverBalfour/obsidian-pandoc#11]
Using a cross platform wrapper around xdg-open ([this](https://github.com/pwnall/node-open) node module looks useful)

Another consideration: with the core Obsidian export to PDF feature, if you've saved as a PDF and still got the PDF open, it still opens a new PDF viewer. The simplest way to work around this is to add an option to disable the auto-open feature in the settings, so you can open it manually.

**Comment by tim-hilde** [comment]
Why was this closed?
