### ISSUE TITLE
No export as pdf option

### ISSUE THREAD

**Issue by hedonihilist** [OliverBalfour/obsidian-pandoc#164]
I installed pandoc and other options like 'epub' and 'latex' show up. But I didn't find the export as pdf option.

Does anyone know what's going on?

![image](https://user-images.githubusercontent.com/76996792/212602995-41a89ab2-0bf6-443e-b685-d5e36aec2e0d.png)

**Comment by ghost** [comment]
Suspect this is linked to https://github.com/OliverBalfour/obsidian-pandoc/issues/119

**Comment by mkwsnyder** [comment]
Running into the same issue, though on an Arch Linux system (pandoc package is `aur/pandoc-bin`).

**Comment by sunsoy** [comment]
Same here on 2 separate ubuntu systems.

pandoc and texlive are in the path, command line pandoc is able to create PDF no problem.

**Comment by hedonihilist** [comment]
Investigated this issue for a while and found that `pdflatex` is required to export as PDF. So if the `pdflatex` is not in PATH, the `Export as PDF` option is not shown.

https://github.com/OliverBalfour/obsidian-pandoc/blob/68ff9e3733cc73055156455721fc736ad45c7d5e/pandoc.ts#L75

**Comment by sunsoy** [comment]
so in my case, flatpak install was causing the problem, despite correct PATH stuff
#158

**Comment by Sharpy17** [comment]
I just had this issue. You need to install MikTex
