### ISSUE TITLE
Pandoc mouse over tooltip truncated for some references

### ISSUE THREAD

**Issue by reemagit** [OliverBalfour/obsidian-pandoc#197]
Hello, the tooltip that appears when one mouse overs a citation is truncated in some cases and doesn't show the top right icon to jump to the literature notes. As in screenshot below:

![image](https://github.com/OliverBalfour/obsidian-pandoc/assets/34165284/a62a6644-9944-483c-bccc-7ae4e85ef5b9)

Can't find what specific citation content causes the bug. Thanks.

**Comment by FeralFlora** [comment]
This tooltip has nothing to do with this plugin, but rather, it's coming from the Pandoc reference list plugin.

**Comment by FeralFlora** [comment]
The bug is due to the url not wrapping. A workaround is to use the setting that replaces the link with an icon. Look in the settings of Pandoc Reference List.

**Comment by reemagit** [comment]
Thanks, that solved it. Also apologies for posting in the wrong place.

**Comment by FeralFlora** [comment]
> Thanks, that solved it. Also apologies for posting in the wrong place.

You're welcome, and no worries, I am just another user.

**Comment by FeralFlora** [comment]
Hey @reemagit, you should close the issue now.
