### ISSUE TITLE
Feature Request: Support for Dataview plugin on a note

### ISSUE THREAD

**Issue by EhuddR** [OliverBalfour/obsidian-pandoc#28]
Hi! I would like to ask if there is any chance to make a dataview plugin integration with the pandoc plugin.

Today I tryed to export a note to html but the plugin show me this in the console.

![image](https://user-images.githubusercontent.com/78237982/117599027-9a38bc00-b10e-11eb-9485-afb9e5b593af.png)

So, in this sense it would be very useful if you could render the kind of notes that have dataview tables and lists with pandoc.

Thanks in advance.

**Comment by OliverBalfour** [comment]
Hmm that's odd, I'll take a look but it might be hard to fix.

**Comment by Quorafind** [comment]
Need this too.

**Comment by OliverBalfour** [comment]
It's currently in a less broken state - it will export notes fine but if you have a dataview list only part of it might be exported (still working on that one 😛)

As I'm quite busy at the moment I won't be able to push a complete fix today but when I do get the chance it shouldn't be too hard to fix

**Comment by EhuddR** [comment]
Thanks! It work great whit some dataview tables I had.
