### ISSUE TITLE
Release as a 'Community Plugin'?

### ISSUE THREAD

**Issue by ryanpcmcquen** [OliverBalfour/obsidian-pandoc#30]
Thank you so much for making this plugin! I love `pandoc`, and was considering writing a plugin for Obsidian with this functionality until I found this one. Are there plans to have it added to the 'Community Plugins' in Obsidian?

**Comment by OliverBalfour** [comment]
Thanks for the kind words!

I have been meaning to add this to the community plugins list for over a month, I've just been bombarded with assignments at university which has throttled development. I intend to pick up development again after the semester ends in a month or so.

I might add this plugin to the community plugins list in the meantime though if I get the chance before then - stay tuned!

**Comment by OliverBalfour** [comment]
Turned out to be much easier than expected. I've submitted it for review, should be easy to install in the app in a week or two.

https://github.com/obsidianmd/obsidian-releases/pull/294
