### ISSUE TITLE
TypeError: i.addChild is not a function

### ISSUE THREAD

**Issue by eleanorkonik** [OliverBalfour/obsidian-pandoc#32]
I tried to export a file (I tried two different files, actually) and got the following error: 

![image](https://user-images.githubusercontent.com/75856959/120074017-c5a52b80-c068-11eb-9e89-30008a1010a9.png)

I tried exporting as .docx using pandoc and the export as html without pandoc option.

**Comment by OliverBalfour** [comment]
Hi @eleanorkonik, do you have DataView installed by chance? If so, it could be #28 cropping up again.

I've just pushed a fix to remove this error but DataView doesn't work fully - it exports the first element of a list sometimes, and for some reason if you embed a note in a note containing a dataview list the list works fine (bizarre, huh?)

Please let me know if this fixes the error, and I'll get DataView working soon

**Comment by eleanorkonik** [comment]
I do indeed have dataview installed. Thanks for the explanation, I can work around that! <3
