### ISSUE TITLE
Possible to include content from other notes in export?

### ISSUE THREAD

**Issue by anthrolisp** [OliverBalfour/obsidian-pandoc#33]
Would it be possible to include content from other documents (possibly through something like https://hackage.haskell.org/package/pandoc-include) in one's conversion/export of a document? For example, if someone composed an essay out of other smaller notes, would be possible to export the entire essay from a single markdown file that pointed to those other notes under different sections?

**Comment by OliverBalfour** [comment]
Yes, you can use Obisidan's embedded note syntax!

Currently I think it only works if all the embedded notes are in the same folder as the main note, but that will be fixed soon. Let me know if you encounter any other issues with it.

Here's an example: if you have `EssayChapter1.md` etc. then the following will include that note when exported:

```md
# My Essay
## Chapter 1
![[EssayChapter1]]
## Chapter 2
![[EssayChapter2]]
## References
![[EssayReferences]]
```
