### ISSUE TITLE
pdf-engine xelatex is not compatible with output format pdf

### ISSUE THREAD

**Issue by damienbelveze** [OliverBalfour/obsidian-pandoc#34]
Hi, 

I have pandoc version 2.7 on my computer and also TexLive (with pdflatex.exe programme inside). 
When I try to export a md note to a pdf note with your plugin (it works in command lines with pandoc), I receive this message : 

"pandoc export failed: pdf-engine xelatex is not compatible with output format pdf"

Please could you tell me how I could solve this problem? 

Regards,

**Comment by OliverBalfour** [comment]
Thanks for reporting this! The only reference I can find to this error is [this](https://github.com/jgm/pandoc/issues/5932) bug report, which indicates updating to Pandoc 2.8 might fix it. If you have time, could you update to the latest Pandoc and let me know if it still doesn't work?

**Comment by OliverBalfour** [comment]
Thanks for reporting this! The only reference I can find to this error is [this](https://github.com/jgm/pandoc/issues/5932) bug report, which indicates updating to Pandoc 2.8 might fix it. If you have time, could you update to the latest Pandoc and let me know if it still doesn't work?

**Comment by damienbelveze** [comment]
Hello, You were right. It worked with Pandoc 2.9. Thank you!
