### ISSUE TITLE
Remove outline indentation before export?

### ISSUE THREAD

**Issue by anthrolisp** [OliverBalfour/obsidian-pandoc#35]
I like to write with Obdisian's outliner plugin, but would like to export the file without the outline markup. Is it possible to automate the removal of outline indentation before export? Thanks!

**Comment by anthrolisp** [comment]
Another thought, is is possible either by pandoc or script to convert an unordered list to an ordered one on export, complete with suborders (1.1, 1.2, 2.1, etc) for nested hierarchies? Ideally this too would be flattened on export. Thanks again!

**Comment by OliverBalfour** [comment]
I don't think this is within the scope of this plugin's core feature set, but I can think of some workarounds:
* For removing outline indentation, you could use a regex find and replace tool. If you're using tabs for indentation then in VSCode for instance you could search `\t` with the regex option on and "replace all" with an empty replacement string
* For converting lists to ordered ones, I am planning to add support for Pandoc filters soon. Then you could use a Pandoc filter for this, either by programming one yourself or finding one online
If you have any further questions just let me know 😃
