### ISSUE TITLE
Can't find Pandoc even though Path has been set - Windows

### ISSUE THREAD

**Issue by vince-vo89** [OliverBalfour/obsidian-pandoc#36]
Hi @OliverBalfour,

I'm a noob user. I reached the settings panel with the pandoc path to the folder which has pandoc application. But it seems that Pandoc is not enabled yet as it says _Pandoc is not installed or accessible on your PATH. This plugin's functionality will be limited._

![image](https://user-images.githubusercontent.com/75612332/121804571-50517180-cc8a-11eb-8807-6a20c699a40e.png)
![image](https://user-images.githubusercontent.com/75612332/121804576-5f382400-cc8a-11eb-96d4-72f8fa4a37c9.png)

Checked again in the terminal:
![image](https://user-images.githubusercontent.com/75612332/121804633-aaeacd80-cc8a-11eb-9627-387d3196a4dd.png)

Thanks Oliver.

**Comment by benytzlich** [comment]
maybe an issue with the path? "Pandoc path: on Windows use the output of 'Get-Command pandoc' -> use that path....
but i experienced a strange behavior too sometimes.

**Comment by OliverBalfour** [comment]
Hmm, odd. I've just tested on my Windows box and it works fine for me. The output of `Get-Command pandoc` on my computer is `C:\Program Files\Pandoc\pandoc.exe`, which works just fine. Do you have any spaces in your path? Have you tried restarting Obsidian after setting the path?
