### ISSUE TITLE
Yaml frontmatter processing

### ISSUE THREAD

**Issue by damienbelveze** [OliverBalfour/obsidian-pandoc#37]
** yaml metadata **

I have noticed that the only metadata from the YAML frontmatter which appears to be processed by the pandoc-obsidian plugin is the title (--metadata title=). Why other elements (subtitle, author, date) do not appear in the PDF ?

Could you tell me please if there is a way to fix it?

Regards,

Damien

**Comment by EhuddR** [comment]
Hi! I have the same issue. There is a way to fix it?

**Comment by OliverBalfour** [comment]
Yes, this should be fixed now. Apologies for the delay!

Let me know if you have any further issues with the YAML frontmatter
