### ISSUE TITLE
Removing links to other obsidian notes in the output (PDF) 

### ISSUE THREAD

**Issue by damienbelveze** [OliverBalfour/obsidian-pandoc#38]
** removing markdown links**

your plugin is released with an awsome feature, the possibility in the settings to choose the way links will be processed. 
When I use pandoc, the output contains links to other notes between brackets. I do not want these links to be active, but I would like the brackets to be removed as well. Do you know how this task is done in your plugin (which part of the command line is responsible for that?)

Regards, 

Damien

**Comment by damienbelveze** [comment]
by adding --from html --to pdf, one can convert a .md file from obsidian to a PDF. Every link to a side-note is converted into text. 
the whole sequence is this one : pandoc 'document.md' --from html --to pdf --pdf-engine=xelatex --citeproc -f markdown+smart -o document.pdf

Please ignore my previous message.

Regards

Damien

**Comment by OliverBalfour** [comment]
All good, glad you've figured it out! This plugin actually works by converting the rendered HTML inside Obsidian to a PDF, rather than using the markdown file itself. That's why it's able to work (partially) with DataView and other plugins.
