### ISSUE TITLE
Warning when exporting footnotes

### ISSUE THREAD

**Issue by tim-hilde** [OliverBalfour/obsidian-pandoc#39]
My literature notes all contain footnotes and therefore I always encounter the following error message when exporting:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/44113468/123212751-77e3dd80-d4c5-11eb-89fb-22c051bb3b3a.png">

**Comment by OliverBalfour** [comment]
Fixed, see the [0.2.2](https://github.com/OliverBalfour/obsidian-pandoc/releases/tag/0.2.2) release. Thanks for reporting this!
