### ISSUE TITLE
Feature request: Removing [[]] links before export

### ISSUE THREAD

**Issue by anthrolisp** [OliverBalfour/obsidian-pandoc#4]
Feature request: Removing [[]] links before export to none hypertext (e.g. odt, docx, etc)

**Comment by OliverBalfour** [comment]
Good idea, I'll probably do this by default. Do you think it should remove links entirely or display the link text as normal text?

**Comment by anthrolisp** [comment]
I imagine a lot of people want to be able to export DOCX and PDF for publication in print where the link will not matter. As such, I would remove it entirely by default, with perhaps an option to display it as a link.

**Comment by SkepticMystic** [comment]
I'd love this as a filter of sorts! Personally, I would want the brackets to disappear, but the note name to stay `[[Note]]` -> `Note`.
Also, my use case would give an alias highest precedence. So `[[Note|Alias]]` -> `Alias`

**Comment by OliverBalfour** [comment]
Okay, what I'll probably do is add a dropdown then with three options:

1. Keep links there (but they don't do anything)
2. Convert links to plain text (giving aliases a higher precedence than note names)
3. Strip links entirely

I think I'll make no. 2 the default setting, as no. 3 is destructive.

**Comment by OliverBalfour** [comment]
Fixed! Here's a screenshot of the new setting:

![image](https://user-images.githubusercontent.com/11626018/114669423-35738700-9d45-11eb-9c8c-221412c6229a.png)

**Comment by FranzKnut** [comment]
This seems to be broken when exporing to PDF? 
I am using version 0.2.5 and the links are treated just as text i.e. resulting in `[[link]]`

**Comment by yanyang1025** [comment]
Even though I've chosen to remove links, after exporting, the document still treats it as text and includes two square brackets. What should I do? Thank you.

**Comment by rokkokoro** [comment]
I have the same issue!

**Comment by rokkokoro** [comment]
> Even though I've chosen to remove links, after exporting, the document still treats it as text and includes two square brackets. What should I do? Thank you.

I have the same issue!

**Comment by zzong2006** [comment]
>Even though I've chosen to remove links, after exporting, the document still treats it as text and includes two square brackets. What should I do? Thank you.

Same issue.
