### ISSUE TITLE
Failed to load plugin obsidian-pandoc-plugin

### ISSUE THREAD

**Issue by damienbelveze** [OliverBalfour/obsidian-pandoc#40]
Hi, 

I have tried to load your last release in my vault but the message I have received was:

"failed to load plugin obsidian-pandoc-plugin"

The plugin cannot be activated in Obsidian. 

Regards.

**Comment by OliverBalfour** [comment]
Hi Damien,

Sorry about that! If you download the `main.js` file from the releases page (https://github.com/OliverBalfour/obsidian-pandoc/releases/download/0.2.1/main.js) and put that in the `.obsidian/plugins/obsidian-pandoc` folder it should work. It looks like the button on GitHub to download a zip doesn't download the files I attached. I'll update the docs to reflect this

**Comment by damienbelveze** [comment]
Thank you very much ! It worked perfectly this time!
