### ISSUE TITLE
Error installing through Community Plugins

### ISSUE THREAD

**Issue by anthrolisp** [OliverBalfour/obsidian-pandoc#45]
"Plugin ID mismatch" error when trying to click on Obsidian-Pandoc plugin through Community Plugins.

**Comment by OliverBalfour** [comment]
Fixed, sorry about that! I just made a typo in the worst possible place - the plugin ID :joy:. If you relaunch Obsidian and press the `Check for updates` button below the `Browse` one (which seems to refresh the plugin list), it should work - I've managed to install it on my computer

Let me know if this doesn't work or you have any further questions 😃
