### ISSUE TITLE
Feature request: export whole folder into dokuwiki with internal links preserved

### ISSUE THREAD

**Issue by bhickta** [OliverBalfour/obsidian-pandoc#46]
## Great Plugin
Great plugin, was wating for this since ages
## Current Issue
* When currently export .md to any format, internal links [[Link]] doesn't work
## Dokuwiki
* Exporting whole folder as .txt files with dokuwiki formatting, one can upload it to dokuwiki server, hence internal links would be preserved
## Benefits
* One can directly publish his/her work on dokuwiki server

**Comment by OliverBalfour** [comment]
Hi, thanks for the suggestions!
I've just published [0.2.4](https://github.com/OliverBalfour/obsidian-pandoc/releases/tag/0.2.4) which has a couple of the features you've requested.

* Exporting internal links: there is a setting called `Internal link processing` which you can try adjusting. If that doesn't work, you can change the `Export files from HTML or markdown?` setting, which will leave wikilinks alone but will stop formatting from other plugins from working
* DokuWiki: I've added this as an export destination, but for now there isn't a batch export feature (relates to #10, #41). This will come soonish

Let me know if you have any issues,
Oliver

**Comment by OliverBalfour** [comment]
Just to clarify: you can get the latest version by updating your plugins inside Obsidian, you don't need to worry about the releases page I linked
