### ISSUE TITLE
Support for mediawiki output

### ISSUE THREAD

**Issue by bjschafer** [OliverBalfour/obsidian-pandoc#51]
The "official" source of documentation at my company is in Mediawiki, but I much prefer to write in Markdown in Obsidian. Sometimes, I need to transform my notes into real documentation, so it'd be great if I could do it via this plugin.

Pandoc supports `mediawiki` as an output format.

Thanks!

**Comment by OliverBalfour** [comment]
Fixed, should work in 0.2.5 (which you can get from the community plugins list). Sorry this tiny change took so long!
