### ISSUE TITLE
export error "unknown option --metadata-file"

### ISSUE THREAD

**Issue by shawngraham** [OliverBalfour/obsidian-pandoc#52]
Hi,

I have pandoc installed through homebrew on a mac. Two issues:

1 - when I export, I get an error: `Unkown option --metadata-file. Try pandoc --help for more information`. When I look at the pandoc help, there's a metadata flag, but not metadata-file. I can find the code in the plugin that specifies --metadata-file and change it to --metadata, and so can at least run the plugin then. 

2. `Pandoc plugin encountered an error trying to load an embedded note: TypeError: Cannot read property 'path' of null`

I'm thinking - since no one else seems to encounter this - that there's something wonky with my pandoc installation.

**Comment by shawngraham** [comment]
ah. I discovered that I have several versions of pandoc on this machine, and that's the source of **both** of my issues. sorry!

**Comment by Jacobxz** [comment]
> ah. I discovered that I have several versions of pandoc on this machine, and that's the source of **both** of my issues. sorry!

  how to slove？
