### ISSUE TITLE
Pandoc export to Docx fails silently when Mermaid has <br> in label

### ISSUE THREAD

**Issue by Willowlark** [OliverBalfour/obsidian-pandoc#53]
Whenever a <br> is included in the label of a mermaid diagram, the pandoc export fails silently. It shows the "exporting to" pop up, then nothing happens. Unsure if there's a way to get more information about that failure.

## Steps to Reproduce

Create document with the following mermaid code block

```mermaid
flowchart LR
Node
Node --> X[[Node<br>Two]]
```

Try to export to Docx.

**Comment by OliverBalfour** [comment]
That's bizarre. I'm not sure how Mermaid works well enough to say what the problem is, but as a workaround you can use `\n` instead of `<br>` to create new lines in Mermaid blocks. I don't think this bug is in my code so there's not a great deal I can do, sorry!
