### ISSUE TITLE
Question: Does the plugin support xelatex and UTF-8 encoding?

### ISSUE THREAD

**Issue by Moonbase59** [OliverBalfour/obsidian-pandoc#55]
Since we have no Discussions enabled here (yet?): I seem to have read somewhere that your plugin supports xelatex—which would be perfect for my use case.

True? How to enable? If automatic, will it prefer xelatex over pdflatex?

**Comment by OliverBalfour** [comment]
Yes, it does, *if* the command `xelatex` doesn't say "command not found" in your terminal. (The relevant code is [here](https://github.com/OliverBalfour/obsidian-pandoc/blob/master/pandoc.ts#L129-L131) if you're interested). I'll add this to the documentation explicitly if it's unclear.

Are you having any issues with the XeLaTeX support or should I close this ticket?

**Comment by Moonbase59** [comment]
Thanks for the info! Will the plugin _prefer_ xelatex if found? (And yes, it is installed and available on the command line, using Linux Mint 20.2 and a rather complete TexLive.)

**Comment by OliverBalfour** [comment]
Yes, if it's present it will use it instead of any alternatives
