### ISSUE TITLE
iOS availability

### ISSUE THREAD

**Issue by soccercoach** [OliverBalfour/obsidian-pandoc#57]
This looks to be a GREAT project and add on for obsidian.

Is there an ETA for this being available for iOS ?

Thanks!

**Comment by OliverBalfour** [comment]
Thanks for the feedback! Unfortunately, Pandoc doesn't natively support iOS or Android and cross-compiling it via GHC.JS to work on iOS is a lot of work and thus out of scope for this project (and it wouldn't support LaTeX PDF's even if I could get Pandoc to work). Sorry for any inconvencience!

**Comment by soccercoach** [comment]
Completely understand.   Had to ask.  :)
Now if I could just figure out a decent workflow to go from Obsidian -> [some workflow] -> Apple Pages (or Word), I'd be golden....
Thanks for your time and efforts!
On Sun, Jul 25, 2021 at 20:31, OliverBalfour  wrote: 
 Thanks for the feedback! Unfortunately, Pandoc doesn't natively support iOS or Android and cross-compiling it via GHC.JS to work on iOS is a lot of work and thus out of scope for this project (and it wouldn't support LaTeX PDF's even if I could get Pandoc to work). Sorry for any inconvenience!

**Comment by darribas** [comment]
Arriving at this after a search for the functionality. Would something like https://github.com/tweag/pandoc-wasm help in this context?
