### ISSUE TITLE
Please Provide an option to convert .md to .txt and viceversa

### ISSUE THREAD

**Issue by skillhacker-code** [OliverBalfour/obsidian-pandoc#60]
Can you please provide an option to convert .md to .txt and .txt to .md .

Thank you so much

**Comment by OliverBalfour** [comment]
Hi,
I originally removed this as Pandoc simply messes up the formatting when converting a md file to a txt file. Markdown files are valid plain text files, so you can just rename the file extension in your file explorer and/or use the [text-as-md](https://github.com/deathau/txt-as-md-obsidian) plugin.
