### ISSUE TITLE
Pandoc is not install or accessible on your PATH. This plugin's functionality will be limited. (Windows 10)

### ISSUE THREAD

**Issue by DKDanielTime** [OliverBalfour/obsidian-pandoc#75]
![image](https://user-images.githubusercontent.com/91132269/134169733-2515a10f-384a-47db-9322-62cd55049205.png)

Hi I using Windows 10 as my OS. I am still pretty new to Obsidian.md and was wondering if anyone could assist with this issue. I have tried reinstalling the plugin, the obsidian.md app, and restarting my computer. I have also reviewed previous similar issues and cannot seem to figure out a solution. I also not sure if this helps but my vault is stored on Microsoft Onedrive. Any assistance would be appreciated.

**Comment by butterflyli** [comment]
Hello,I met the same trouble.But after I set the path as '……\pandoc.exe' and rerun the Obsidian program, this plugin can work properly.

**Comment by fatkc** [comment]
What happens if `$ Get-Command pandoc` doesn't yield any path?
