### ISSUE TITLE
Add file saving dialog instead of automatically choosing a save location?

### ISSUE THREAD

**Issue by OliverBalfour** [OliverBalfour/obsidian-pandoc#8]
I might make showing a dialog a toggle-able setting, as I quite like being able to just choose an option without worrying about where the file should go.

**Comment by Mara-Li** [comment]
Also : 
- set an option in parameters to set an automatic folder to export.
- Set an option to export in the same folder as the original
- Set an option to export in obsidian vault root.

**Comment by OliverBalfour** [comment]
I might add a "default export folder" setting and make the default the root of the obsidian vault. This will probably come before adding a file save dialog.

When you say "in the same folder as the original" do you mean if you export a file `vault/subfolder/file.md` you want it in `vault/subfolder/file.md`? I thought it did that, or does it put it in the vault root?

**Comment by Mara-Li** [comment]
For the moment, each export is in the root vault, yes, not in the same folder of the original file ^^

I was more thinking about parameters in the plugin than dialog (because I hate dialogs).

**Comment by OliverBalfour** [comment]
That's a bug then, must've missed it as my folder structure is flat.

Given I'm not too keen on dialogs either, I'll restrict it to just a plugin setting which will also save some time.

Closing in favour of #25
