### ISSUE TITLE
Is it possible to specify an output directory?

### ISSUE THREAD

**Issue by seatrout** [OliverBalfour/obsidian-pandoc#83]
Apologies if this is a really silly question, but I would like to be able to specify the output directory for particular conversions (perhaps in the YAML) so that if I write an article in Obsidian the resulting copy is stored in same folder as under the system set up with a full-blown word processor. Could this be possible? I had a quick, ignorant, scan of the code and couldn't see anywhere that the output directory was specified.

**Comment by ArwensAbendstern** [comment]
@seatrout apologies if I misread your requirements, first time responder… 
Have you seen the Export Folder option in the settings under Obsidian Settings → PLUGIN OPTIONS → Pandoc Plugin → scroll down a bit to see the "Export folder": this is not specific for a particular conversion but at least allows you to set a common export folder for all export files. 
![Obsidian Pandoc Export folder Screenshot 2021-11-27 at 14 18 10](https://user-images.githubusercontent.com/795540/143685368-0133c8d6-8348-48fa-9451-9fdc93a8489d.png)
Perhaps this could be extended to allow diff export paths for specific export formats in future…
Hope this helps.

**Comment by seatrout** [comment]
Thanks! I had missed that. But it makes life much easier
